import {
  AlignSelfProps,
  BordersProps,
  BottomProps,
  ColorProps,
  FlexProps,
  FontSizeProps,
  GridAreaProps,
  LayoutProps,
  LeftProps,
  OrderProps,
  PositionProps,
  RightProps,
  SpaceProps,
  TextAlignProps,
  TopProps,
  ZIndexProps,
} from 'styled-system';

export interface ICommonBox
  extends AlignSelfProps,
    BordersProps,
    BottomProps,
    ColorProps,
    FlexProps,
    FontSizeProps,
    GridAreaProps,
    LeftProps,
    OrderProps,
    PositionProps,
    RightProps,
    SpaceProps,
    TopProps,
    ZIndexProps,
    LayoutProps,
    TextAlignProps {}
