export enum SALE_STATUS {
  NOT_CONNECTED_WALLET = 'NOT_CONNECTED_WALLET',
  NOT_STARTED = 'NOT_STARTED',
  HAS_CLAIMED = 'HAS_CLAIMED',
  FREE_CLAIM = 'FREE_CLAIM',
  PREMIUM_CLAIM = 'PREMIUM_CLAIM',
  SOLD_OUT = 'SOLD_OUT',
  EXPIRED = 'EXPIRED',
}
